/*
 * Copyright (c) 2026 Vidocq contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 */
package io.vidocq.cassini.client.internal;

import jakarta.ws.rs.client.AsyncInvoker;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.InvocationCallback;
import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

/**
 * Implementation of {@link AsyncInvoker} based on {@link CompletableFuture} +
 * virtual threads. Each method delegates to the corresponding sync method of
 * {@link CassiniInvocationBuilder}, executing it in a virtual thread.
 *
 * <p>The CLIENT filter pipeline (request/response) runs entirely in the async
 * thread — the {@code kind=CLIENT} spans set by
 * {@code HumboldtClientRequestFilter}/{@code HumboldtClientResponseFilter} are thus
 * correctly created and terminated around each async call.</p>
 *
 * <p>{@link InvocationCallback}: the {@code completed(T)} method is invoked on
 * success, {@code failed(Throwable)} on HTTP I/O error.</p>
 */
final class CassiniAsyncInvoker implements AsyncInvoker {

    private final CassiniInvocationBuilder builder;
    private final Executor executor;

    CassiniAsyncInvoker(CassiniInvocationBuilder builder) {
        this.builder = builder;
        this.executor = Executors.newVirtualThreadPerTaskExecutor();
    }

    // ---- helpers ---------------------------------------------------------------------------

    /**
     * Captures the current {@code io.opentelemetry.context.Context} (if OTel is on the
     * classpath via {@link AsyncContextPropagator}) and re-attaches it in the async
     * thread. Without this, the CLIENT span generated by the OTel humboldt-rest filters
     * in the async thread would be root and the SERVER → CLIENT → SERVER target span
     * chain would be broken. Cassini-client remains decoupled from OTel thanks to reflection.
     */
    private Future<Response> async(String method, Entity<?> entity) {
        Object ctx = AsyncContextPropagator.capture();
        return CompletableFuture.supplyAsync(() -> {
            try (var scope = AsyncContextPropagator.activate(ctx)) {
                return builder.invoke(method, entity);
            } catch (Exception e) { throw new RuntimeException(e); }
        }, executor);
    }

    @SuppressWarnings("unchecked")
    private <T> Future<T> asyncTyped(String method, Entity<?> entity, Class<T> type) {
        Object ctx = AsyncContextPropagator.capture();
        return CompletableFuture.supplyAsync(() -> {
            try (var scope = AsyncContextPropagator.activate(ctx)) {
                Response r = builder.invoke(method, entity);
                throwIfErrorStatus(r);
                return (T) r.readEntity(type);
            } catch (jakarta.ws.rs.WebApplicationException wae) {
                throw wae;  // Propagate as-is so Future.get() exposes via ExecutionException.getCause()
            } catch (Exception e) { throw new RuntimeException(e); }
        }, executor);
    }

    @SuppressWarnings("unchecked")
    private <T> Future<T> asyncTyped(String method, Entity<?> entity, GenericType<T> type) {
        Object ctx = AsyncContextPropagator.capture();
        return CompletableFuture.supplyAsync(() -> {
            try (var scope = AsyncContextPropagator.activate(ctx)) {
                Response r = builder.invoke(method, entity);
                throwIfErrorStatus(r);
                return (T) r.readEntity(type.getRawType());
            } catch (jakarta.ws.rs.WebApplicationException wae) {
                throw wae;
            } catch (Exception e) { throw new RuntimeException(e); }
        }, executor);
    }

    /**
     * Spec JAX-RS §5.6 — when a non-null entity type is requested and the response
     * has an error status (≥400), throw {@link jakarta.ws.rs.WebApplicationException}
     * (or a specialized subclass depending on the status code, e.g. NotFoundException for 404).
     */
    private static void throwIfErrorStatus(Response r) {
        int s = r.getStatus();
        if (s < 400) return;
        throw new jakarta.ws.rs.WebApplicationException("HTTP " + s, r);
    }

    private <T> Future<T> asyncCallback(String method, Entity<?> entity, InvocationCallback<T> callback) {
        Object ctx = AsyncContextPropagator.capture();
        CompletableFuture<T> future = CompletableFuture.supplyAsync(() -> {
            try (var scope = AsyncContextPropagator.activate(ctx)) {
                @SuppressWarnings("unchecked")
                T result = (T) builder.invoke(method, entity);
                return result;
            } catch (Exception e) { throw new RuntimeException(e); }
        }, executor);
        future.whenComplete((res, ex) -> {
            if (ex != null) callback.failed(ex);
            else callback.completed(res);
        });
        return future;
    }

    // ---- GET -------------------------------------------------------------------------------

    @Override public Future<Response> get() { return async("GET", null); }
    @Override public <T> Future<T> get(Class<T> type) { return asyncTyped("GET", null, type); }
    @Override public <T> Future<T> get(GenericType<T> type) { return asyncTyped("GET", null, type); }
    @Override public <T> Future<T> get(InvocationCallback<T> cb) { return asyncCallback("GET", null, cb); }

    // ---- PUT -------------------------------------------------------------------------------

    @Override public Future<Response> put(Entity<?> e) { return async("PUT", e); }
    @Override public <T> Future<T> put(Entity<?> e, Class<T> type) { return asyncTyped("PUT", e, type); }
    @Override public <T> Future<T> put(Entity<?> e, GenericType<T> type) { return asyncTyped("PUT", e, type); }
    @Override public <T> Future<T> put(Entity<?> e, InvocationCallback<T> cb) { return asyncCallback("PUT", e, cb); }

    // ---- POST ------------------------------------------------------------------------------

    @Override public Future<Response> post(Entity<?> e) { return async("POST", e); }
    @Override public <T> Future<T> post(Entity<?> e, Class<T> type) { return asyncTyped("POST", e, type); }
    @Override public <T> Future<T> post(Entity<?> e, GenericType<T> type) { return asyncTyped("POST", e, type); }
    @Override public <T> Future<T> post(Entity<?> e, InvocationCallback<T> cb) { return asyncCallback("POST", e, cb); }

    // ---- DELETE ----------------------------------------------------------------------------

    @Override public Future<Response> delete() { return async("DELETE", null); }
    @Override public <T> Future<T> delete(Class<T> type) { return asyncTyped("DELETE", null, type); }
    @Override public <T> Future<T> delete(GenericType<T> type) { return asyncTyped("DELETE", null, type); }
    @Override public <T> Future<T> delete(InvocationCallback<T> cb) { return asyncCallback("DELETE", null, cb); }

    // ---- HEAD ------------------------------------------------------------------------------

    @Override public Future<Response> head() { return async("HEAD", null); }
    @Override public Future<Response> head(InvocationCallback<Response> cb) { return asyncCallback("HEAD", null, cb); }

    // ---- OPTIONS ---------------------------------------------------------------------------

    @Override public Future<Response> options() { return async("OPTIONS", null); }
    @Override public <T> Future<T> options(Class<T> type) { return asyncTyped("OPTIONS", null, type); }
    @Override public <T> Future<T> options(GenericType<T> type) { return asyncTyped("OPTIONS", null, type); }
    @Override public <T> Future<T> options(InvocationCallback<T> cb) { return asyncCallback("OPTIONS", null, cb); }

    // ---- TRACE -----------------------------------------------------------------------------

    @Override public Future<Response> trace() { return async("TRACE", null); }
    @Override public <T> Future<T> trace(Class<T> type) { return asyncTyped("TRACE", null, type); }
    @Override public <T> Future<T> trace(GenericType<T> type) { return asyncTyped("TRACE", null, type); }
    @Override public <T> Future<T> trace(InvocationCallback<T> cb) { return asyncCallback("TRACE", null, cb); }

    // ---- method() --------------------------------------------------------------------------

    @Override public Future<Response> method(String name) { return async(name, null); }
    @Override public <T> Future<T> method(String name, Class<T> type) { return asyncTyped(name, null, type); }
    @Override public <T> Future<T> method(String name, GenericType<T> type) { return asyncTyped(name, null, type); }
    @Override public <T> Future<T> method(String name, InvocationCallback<T> cb) { return asyncCallback(name, null, cb); }
    @Override public Future<Response> method(String name, Entity<?> e) { return async(name, e); }
    @Override public <T> Future<T> method(String name, Entity<?> e, Class<T> type) { return asyncTyped(name, e, type); }
    @Override public <T> Future<T> method(String name, Entity<?> e, GenericType<T> type) { return asyncTyped(name, e, type); }
    @Override public <T> Future<T> method(String name, Entity<?> e, InvocationCallback<T> cb) { return asyncCallback(name, e, cb); }
}
